/**
 * Created by xiaoming on 2018/1/26.
 */

export const NAVIGATOR_NAVIGATE = 'NAVIGATOR_NAVIGATE';
export const NAVIGATOR_RESET = 'NAVIGATOR_RESET';
export const NAVIGATOR_REPLACE = 'NAVIGATOR_REPLACE';

export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILED = 'REQUEST_DATA_FAILED';
export const REFRESH_DATA = 'REFRESH_DATA';
export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';